# export EVENTBRIDGE_EXAMPLE_SERVICE=my-eventbridge
service: ${self:custom.serviceName}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ${self:custom.serviceRegion}
  logRetentionInDays: 7
  versionFunctions: false

  environment:
    eventBusName: ${self:custom.eventBusName}
    serviceRegion: ${self:custom.serviceRegion}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "events:PutEvents"
      Resource: "*"

package:
  exclude:
    - node_modules/aws-sdk/**

custom:
  serviceName: ${env:EVENTBRIDGE_EXAMPLE_SERVICE, "eventbridge-example"}
  eventBusName: ${env:EVENTBRIDGE_EXAMPLE_BUSNAME, "${self:service}-${self:provider.stage}-bus"}
  serviceRegion: ${env:EVENTBRIDGE_EXAMPLE_REGION, "eu-west-1"}
  eventBusArn:
    Fn::Join:
    - ''
    - - 'arn:aws:events:'
      - Ref: 'AWS::Region'
      - ':'
      - Ref: 'AWS::AccountId'
      - ':event-bus/'
      - ${self:service}
      - '-'
      - ${self:provider.stage}
      - '-'
      - 'bus'

functions:
  Consumer:
    handler: src/lambda/main_service/Consumer.handler
    events:
     - eventBridge:
        eventBus: ${self:custom.eventBusName}
        pattern:
           source:
             - dennis.experimental.event

  Producer:
    handler: src/lambda/main_service/Producer.handler

resources:
  Outputs:
    ExampleBus:
      Value: ${self:custom.eventBusArn}
      Export:
        Name: ExampleBus
